---
title: "Book Recommendations"
---

## Recommendations
I like recommending books to other people, and find that the best way to get good new recommendations is to find someone with overlapping tastes and then look for ones they like that I haven't read yet. In that spirit, here are some books/authors I've enjoyed that I can recommend:

#### Sci-fi:
- Anything by Asimov, anything by Douglas Adams (classics)
- Anything by John Scalzi. "Lock In" if you want more gritty detective action, "Do Androids Dream of Electric Sheep" for something more absurd and funny, "old man's war" for a good series
- The Three Body Problem (dark forest trilogy) by Cixin Liu is excellent sci-fi from a different perspective, loved it
- Seveneves by Neal Stevenson is great, as is lots of his other work
- The Martian and its sequels are fun, by Andy Weir

#### Fantasy:
- I like the Stormlight series from Brandon Sanderson. 
- Discworld series by Pratchett 

#### Non-fiction:
- The Righteous Mind: a fantastic book for understanding morality+religion. Can't recommend this highly enough. If you skip the book at least read his paper "The Emotional Dog and its Rational Tail".
- Reality + by David Chalmers: philosophy of mind through a modern lens, great overview of lots of philosophy topics and an excellent defence of simulation realism
- An Immense World by Ed Young, one of my favorite books. Animal senses and how their words differ from ours. Mind expanding.
- The Seabird's Cry. Poignant look at amazing creatures and how we're changing their world, with a very poetic author. 
- I am a strange loop: Fun to see someone tackle an ambitious question for a second time (this is the same author as Godel, Escher, Bach). Be prepared for many long diversions and analogies as he tries to make his meaning unambiguous.

## Others (WIP)

In no particular order, here are a bunch of others I've read. As I read more I'm adding them to the top of this list, with mini-reviews. The bulk of the list is still just me trying to remember as many as possible, and should grow + become more orderly over time.

- Children of Time. Keeps getting recommended to me since I like Jumping Spiders. Glad I got around to it - excellent exploration of a different tech-tree from a non-human POV. Sad view of humanity haha.
- Birding without borders (Noah Strycker) - Account of an amazing achievement. Around the world, 6k birds for $60k. What a way to spend a year! Gives you a little glimpse of the world and a large glimpse of birds and birders.
- (TODO what else did I read in this gap?)
- Winds Twelve Quarters (Ursula K. Le Guin) - fantastic short stories, I really enjoy her work. 
- Fractal Noise - A 'short story' that is maybe longer than it needs to be, although in his defence he'd just written the Eragon series. 
- Lock In (John Scalzi) - Thrilling detective story in a fun world, both it and the sequel were fun to re-visit amid the online speculation re: Neuralink and the general AI discourse even though the main plot isn't much focused on the tech.
- What We Owe The Future. I finally read this after being a little frustrated with some longtermist takes. Annoyingly, Will is more reasonable than the loonies and the book was fairly interesting and well-written. I think I would have enjoyed it more if I hadn't already been over the ideas a ton - if you're less familiar with the ground it might be a good intro to this patch of philosophy and population ethics. 
- The Tale of the Dueling Neurosurgeons (Sam Kean). This author writes history very well - the parade of case-studies can get a little tiring but you do get sucked into the individual stories alongside a healthy dose of neuroscience (albeit not extremely deep technically).
- At The Existentialist Cafe (Sarah Bakewell). TODO.
- Old Man's War (John Scalzi) A fun series, humanity in a 'Starship Troopers'-like universe where you're never quite sure if humans are really the baddies.
- Going Zero (Anthony McCarten) Quick read, thanks to TITAA for the rec. Thriller, exploring surveillance and the dangers of power concentrated in the hands of SV elite types. 
- The Tao of Pooh. Great fun, worth a skim. The author has a very scathing view of scientists! 
- Determined (Robert Sapolsky). I enjoyed his course. The book is his ultimate debunk of the idea of free will, followed by an exploration of what that means in practice for how we should live. I enjoyed it but it's snarkily written to the point of being off-putting for anyone not already on board with the idea - I don't think this would be very useful for convincing someone to change their mind.
- The Interdependency Trilogy (Scalzi). Future space civilizations, my least favourite of his. A few neat ideas, lots of inner thoughts of non-so-nice people. 
- The Kaiju Preservation society (Scalzi). A great read, very much in his style. Made me laugh out loud, which few authors manage. Also completely ridiculous but then this is Scalzi...
- I Contain Multitudes (Ed Young). He writes really well. I was skeptical because 'microbiome' is so trendy, turns out this book started the craze and is a lot more measured and realistic than some subsequent hype. Hard not to get excited about bacteria after reading this :)
- Klara and the Sun. Interesting book. Had me thinking a fair amount about how willing humans are to ascribe human-like intelligence and other qualities to very foreign things. See also: thinking jumping spiders are cute, pair-bonding with anything that has googley eyes. My family tried to turn this into a book club but stretched the discussion out too far. I did like his attempt to show Klara's strange way of perceiving the world - how some things are, to her, obviously evil - much like my dog hates lawnmowers. Scary as we imagine future more competent yet foreign intelligences.
- Entangled Life (Martin Sheldrake). Great read re: fungi, fun to get a picture of the author as your read through their work.
- Strange Rites - New Religions for a Godless Age (author name). Fascinating dive into some contemporary 'religions', providing a useful lens for understanding a lot of things in the world today. 
- The Mistborn Trilogy (Brandon Sanderson). Not as good as his Stormlight series but I persevered. Worth a go if you're fantasy-starved and like Sanderson. 
- Mindful Eating (Jan Chozen Bays). A reminder to slow down and savor things. A little weird and 'extra' but it's their book, fair game. 
- Into the Wild (Jon Krakauer). A fascinating account of an interesting individual and his conflict with society. I'm always interested in anyone who refuses to walk the default path. 
- The Alchemist (Paulo Coelho). I fondly remember a teacher read this to us in junior school. Manifest destiny and all that - interesting to think about, and seemingly fairly popular, but easy to take too far.
- "Happy Money: The Science of Smarter Spending" (Elizabeth Dunn, Michael Norton). Fun in a Freakonomics-wannabe sort of way. Take the book's own recommendation to buy time by skipping reading it and instead just ask ChatGPT to summarize the key actionable ideas.
- "All That the Rain Promises and More" (David Arora). A highly entertaining field guide for mushrooms, sprinkled with fantastic anecdotes and tasting notes. Mandatory for trips around Oregon!
- DUNE (Frank Herbert) and sequels. Interesting and genre-defining in some ways. The sequels got a little too weird for me. 
- "The End of the World Is Just the Beginning" (Peter Zeihan). Read it because it challenges my optimistic outlook. Reveals a lot about the interdependence we have through globalization, and how fragile these systems are. And made me more aware of America and their role in the world.
- How To Be A Stoic (Massimo Pugliochi???). I like Stoicism, and think it should be much more popular. The book does a good job giving actionable tips in addition to condensing key ideas.
- Man's Search for Meaning (Viktor Frankel) - Underwhelming given the praise I've seen for it, but does make the point well that humans seem to want meaning :shrug:
- Are We Smart Enough to Know How Smart Animals Are? (Frans de Waal)
- The Count of Monte Christo - loved this classic TODO re-read and review.
- Discworld Series (Terry Pratchett). I've read all of these multiple times, such witty commentary on life.
- Douglas Adams
- Christopher Paolini
- F.W. Dixon
- Willard Price
- Tolkein
- Brian Jaques
- Enid Blighton
- Bill Bryson
- Anthony Horowitz (Alex series)
- Popco
- Liveship trilogy
- Guns, germs and steel (todo sequel 'collapse' to talk to FIL)
- You are not so smart and sequel
- Goosebumps (a handful)
- CUrious incident of the dog in the nighttime
- John Wyndham (midwich cuckoos, triffids, a few others)
- White fang and the call of the wild Jack London
- Chicken soup for the preteen soul
- The bible (several re-reads, lots of excerpts)
- Freakonomics and sequel
- How to spend X and do Y bjorn lomberg
- Shakespeare (a few) and tales from shakespeare (banger)
- Ignition (great book)
- Bell Labs: Innovation Factory great
- Surely You're Joking Mr Feynman (3+ reads, impactful)
- 6 easy pieces, 6 hard ones, QED by him too
- A brief history of time and even briefer one
- Astrophysics for people in a hurry
- Skimmed thinking fast and slow, blink, think again and similar selg-help books
- That crazy magical realism one about the SA village family
- Tim Keller marriage book
- That other marriage book
- Bird book haha
- The silent knife thing (lame)
- The Hunger Games
- That rip-off hunger games post apocalyptic one Ellie makes fun of
- Make: the annotated build-it yourself
- Making Embedded Systems
- Laws guide to nature drawing and journalling
- Reality + 
- P. G. Woodhouse  (most if not all, several reads of Jeeves)
- James Herriot (funny vet)
- The doctor equivalent 'A Doctor Abroad' maybe?
- Wilderness ways lovely
- Gerrald Durrel problematic
- The 100-year-old man who climbed out of his window and the sequel about the girl who saved the king of Sweden hilarious
- The Rosie Project good laugh
- Dr Seuss
- S>A>S survival guide
- Hatchett or something recd by E, that or my side of the mountain only one of the two
- The Call of the wild (that guy who went into the woods)
- Some Agatha Christie
- Some Nancy drew maybe? Definitely a crossover with Hardy BOys IIRC
- 'MLP: Friendship is optimal' and some others on a weird list Hotz shared
- That space series with a magical ship AI nanobots and such
- 'Hothouse' parasitic mind control scifi find author (I read several IIRC)
- Scifi anthology
- Science of the DIscworld
- The Long Earth Series
- The magic compass (trilogy, knife somethig something)
- Ball Lightning and the Three Body trilogy
- Sci-fi/horror theres a deep hole up come *wasps* or something, biological control for humans?
- Outlive by Peter Attia
- Eat food, not too much, mostly vegetables (Michael Pollen?)
- Lab Girl (boring)
- Three Men on a bummel
- Once upo a river magical realism
- Dandelion Wine (Ray Bradbury)
- Farenheight 451
- A Brave New World
- Trooper Peter Halket?
- Wet Breams and sequel elephant guy
- That one with the SA people who owned a lion? 
- Oh that weird AI thinkpiece by Kissenger and co that didn't say much
- Public Health in mid-VIctorian Britain
- Grades, Sub-grades and Subbases (or subsomethings at least)
- South Africa's Vanishing Waterways
- Why_'s poignant Guide to Ruby
- Pride and Prejudice
- The Idea Factory, Bell Labs 
- Make: The Annotated DIY Science Laboratory (hilarious safety warnings)
- Make: Tips and Tales from the workshop
- Roberts Field Guide to Birds of Southern Africa
- Windmills (Jaap's book)
- You are Not So Smart + You Are Now Less Dumb (also enjoyed the podcast)
- Tales from Shakespeare (Charles Lamb) - fantastic re-telling of Shakespeare's plays as short stories, keeping in many good quotes and otherwise adapting them very well. 
- 1984 
- Tess of D'Uberville
- Far from the madding crowd
- Pride and Prejudice
- Don Qiote (spelling?)
- Jade City and possibly sequels
- THe man who mistook his wife for a hat