---
title: "That Should Be A Band Name"
---

The following are phrases that have come up organically in my vicinity that make us think 'That should be a band name!' 

Enjoy :)

Frantic meditation

Seismic upgrades

Potato expert

Detours for Whimsy

Cheerfully seedy

Deference to my heiny 

Concrete brownies 

Alter-Eggo

Red-headed Noise Makers

Scooters On Ice

Hunka Munka Suburbs

The spleen is discontent

Ancestral Fluff

DIY Dentistry 

The Principal's Special Breakdown

Serious Bodices

Post hoc dodge / Post after the fact

Bossed around by a bench 

The inescapable cowboy Jesus mural

Santa baby Zipline 

Dump and rummage

Paninis and pushups 

Post-hoc Portmanteau

Modern and current snacks

Words from the walls

Not cranky just creaky

Handsome Hippo in Charge

Maximalist Sprinkles

Random perturbations

Bony landmarks 

Basement biology

Administrative foofoo

Exploratory squishage

Pacifist satanists 

Hearse full of concrete 

Multiple dangles

Urban radagast

Robot flamingos

Indiscriminate muffin eaters

Evil misogyny and black mold

Emergency Icecream

Teacups and textbooks 

Curse carpentry 

Loose leaf from the other side

Nonconforming triplex

Groggiest blog

Feet on the florist

Purple cat butt phenotype

Non-Euclidian Vlogging

Bidirectional Belly-Blathering

Soggy Biscotti 

Woo poop to the family group 

Hydrodynamic ankles

Contemplating my descent 

Declining mouthfuls of mammoth 

Squishchief

Midnight disaster 

Nibbly bits

Friction Penguin

Something about the monkey 

Hunky Monkey 

Chaos Bunnies 

Emotional blender 

Exactlyish

Non-consensual Monologing

Bouncy Castle in My Mind

Octogenarian boyfriends 

Lip extensions

Random Acts of Kazoo

Seven Minutes of Strife

No Small Line of Hipsters

Conspiracy of Big Packaging

Holiday Hoo-Hah

Serious Hops

(Far Away From Your) Bedside Ants

Taxidermy Rock

The Last Batch

Heat Shrink Butt Connectors

Cytoplasmic Imperatives

Small Amounts of Stabbage

Glorious Turkeys Dear

Pigeon Religion

Glabrous Bracts

Incidental Cereal

(The) Lovely Scraps

Ambient Cats

Sob in a Bog

Exuberant Hoots

Eye Candy Uncle

Moistrous

Projectile Summer

N'Oubliez Pas Le Fromage

Minimum Wage Robots

Individual Blob(s)

Soggly Load